### ISSUE TITLE
Create Dummy Data Table for Front End Folks

### ISSUE THREAD

**Issue by JoeyHoellerich** [JoeyHoellerich/Toned#16]
Should be formatted the same as the server response

**Comment by jjlee90** [comment]
{
    "exercises": [
        {
            "_id": "62ec22c5b1bb9a6fd48408bc",
            "workout": "Squat",
            "sets": "1",
            "reps": "5",
            "weight": "225"
        },
        {
            "_id": "62ec3596b1bb9a6fd48408be",
            "workout": "pushUps",
            "sets": "3",
            "reps": "20",
            "weight": "0"
        },
        {
            "_id": "62ec46f2b1bb9a6fd48408c5",
            "workout": "Pull-Ups",
            "sets": "3",
            "reps": "10",
            "weight": "0"
        },
        {
            "_id": "62ec4795b1bb9a6fd48408c6",
            "workout": "Leg Press",
            "sets": "3",
            "reps": "10",
            "weight": "180"
        },
        {
            "_id": "62ed455c109b07c583de97a2",
            "workout": "Squat",
            "sets": "1",
            "reps": "10",
            "weight": "135"
        },
        {
            "_id": "62ed4689109b07c583de97a3",
            "workout": "Bench Press",
            "sets": "1",
            "reps": "10",
            "weight": "135"
        },
        {
            "_id": "62ed7cc2be5fec0913f8852b",
            "workout": "Push-Ups",
            "sets": "1",
            "reps": "25",
            "weight": "0"
        }
    ]
}

**Comment by JoeyHoellerich** [comment]
file can be found /client/data/dummydata.js
