### ISSUE TITLE
Mockup for Front End of Toned

### ISSUE THREAD

**Issue by JoeyHoellerich** [JoeyHoellerich/Toned#4]
**Front End/UI**

- Mobile-First (design app to run well on mobile devices)
- Navbar (0)
- ‘Login Screen’ - make sure only to get your own data (1)
    - Sign Up Button
- 'Sign Up Screen' 
    - Username input field
    - Create Account Button
- Welcome Page - Charts/Graphs/Tables of previous data (2)
    - Something different if no data tied to user
    - New Workout Button 
- Add New Workout Page (3)
    - Weight
    - Sets
    - Reps
- View Past Workouts (4)
    - Simple table with simple filters
    - View/Edit Details
- Edit Past Workouts (5)
    - Update 
        - Weight
        - Sets
        - Reps
        - Date
- Delete (6)
    - Confirm Delete

**Comment by WaffleKone** [comment]
Edit: Added 'Create Account' Page option to the requirements list, we completely forgot about it lol

**Comment by JoeyHoellerich** [comment]
Completed Mockup
