### ISSUE TITLE
Determine What Data will be stored + Database structure

### ISSUE THREAD

**Issue by JoeyHoellerich** [JoeyHoellerich/Toned#5]
Diagram of how data will be structured, and what data is being collected

**Comment by jjlee90** [comment]
![toned-data-structure-Page-2 drawio](https://user-images.githubusercontent.com/95702793/183232492-00f42cf1-aee2-475d-8448-de2ce909a983.png)

**Comment by WaffleKone** [comment]
Completed by Joseph
